FROM alpine:3.6

# Maintainer 
MAINTAINER Ben M <git@bmagg.com>

# Configuration
ENV DOCUMENT_ROOT="/app/public" \
  UPLOAD_MAX_FILESIZE="2M" \
  POST_MAX_SIZE="8M" \
  MEMORY_LIMIT="128M" \
  TIMEZONE="UTC" 

# Fix volume mount permissions issues
RUN set -x \
  && addgroup -g 50 -S www-data \
  && adduser -u 1000 -D -S -G www-data www-data 

# Install some dependencies
RUN apk --update add \
  supervisor \
  nginx \
  nano \
  curl \
  php7 \
  php7-common \
  php7-fpm \
  php7-fileinfo \
  php7-bcmath \
  php7-dom \
  php7-ctype \
  php7-curl \
  php7-gd \
  php7-iconv \
  php7-intl \
  php7-json \
  php7-mbstring \
  php7-mcrypt \
  php7-mysqlnd \
  php7-opcache \
  php7-openssl \
  php7-pdo \
  php7-pdo_mysql \
  php7-pdo_pgsql \
  php7-pdo_sqlite \
  php7-phar \
  php7-posix \
  php7-session \
  php7-soap \
  php7-tokenizer \
  php7-xml \
  php7-xmlreader \
  php7-xmlwriter \
  php7-zip \
  php7-zlib \
  php7-ldap \
  && rm -rf /var/cache/apk/*

# Add start script
ADD start /usr/local/bin/
RUN chmod +x /usr/local/bin/start

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configure nginx
ADD conf/nginx.conf /etc/nginx/
RUN chmod -R 755 /var/tmp/nginx

# Configure php-fpm
ADD conf/php-fpm.conf /etc/php7/
ADD conf/php.ini /etc/php7/

# Configure supervisor
ADD conf/supervisord.conf /etc/supervisor/conf.d/

# Set our workdir
WORKDIR /app

# Expose ports
EXPOSE 80 443

# Build something amazing
CMD ["sh", "/usr/local/bin/start"]