#!/bin/bash

# Copy env vars to env.conf file for nginx
echo " ---> Passing environment vars to nginx"
sh /usr/local/bin/copyenv

# Run additional build commands
echo " ---> Executing build commands"
if eval $BUILD_COMMANDS
then
	echo " ---> Successfully executed build commands"
else 
	echo ERROR: Failed to execute build commands
	exit 1 # terminate and inidcate error
fi

# Start supervisor 
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf